### ISSUE TITLE
support Groups feature

### ISSUE THREAD

**Issue by mikestaub** [immers-space/immers#8]
This is the biggest problem in the Fediverse right now and it needs to be tackled head-on for there to be any success.

https://github.com/tootsuite/mastodon/issues/139

**Comment by wmurphyrd** [comment]
Mike, please check out my federated groups project that works across platforms: https://github.com/wmurphyrd/guppe
Also, there's new groups apps from QOTO: https://groups.qoto.org/about/more
And from Framasoft: https://joinmobilizon.org/en/

I don't know if there's a need for group implementation within immers itself, but it's not on our near-term roadmap. Thanks
